import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import CountryProvider from '@/context/CountryContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Rest countries',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CountryProvider>
          <Header />
            {children}
        </CountryProvider>
        </body>
    </html>
  )
}
